[package]
authors = ["Anthony DiMarco <ocramida@gmail.com>", "Jimmy Cuadra <jimmy@jimmycuadra.com>", "Matthew Mayer <matthewkmayer@gmail.com>", "Nikita Pekin <contact@nikitapek.in>"]
description = "AWS SDK for Rust - Amazon Kinesis Video Streams Archived Media @ 2017-09-30"
documentation = "https://docs.rs/rusoto_kinesis_video_archived_media"
keywords = ["AWS", "Amazon", "kinesis-video-archiv"]
license = "MIT"
name = "rusoto_kinesis_video_archived_media"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.48.0"
homepage = "https://www.rusoto.org/"
edition = "2018"
exclude = ["test_resources/*"]
[package.metadata.docs.rs]
targets = []

[build-dependencies]

[dependencies]
rusoto_core = "0.48.0"
async-trait = "0.1"
bytes = "1.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0"

[dependencies.futures]
version = "0.3"

[dev-dependencies]
tokio = "1.0"

[features]
default = ["native-tls"]
deserialize_structs = ["bytes/serde"]
native-tls = ["rusoto_core/native-tls"]
rustls = ["rusoto_core/rustls"]
serialize_structs = ["bytes/serde"]
